### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by hit-joseph** [pengli09/str2vec#4]
Hi, when I run the command ,I meet the problem
./mpi-train.sh 10
Instances file: /users4/xyan/experiment/phrase/phrase_vec_embedding/str2vec-master/demo-data/str2vec-demo/input/sample-training-file.txt
Model file: /users4/xyan/experiment/phrase/phrase_vec_embedding/str2vec-master/demo-data/str2vec-demo/output/sample-training-file.mpi-10.model.gz
Word vector file: /users4/xyan/experiment/phrase/phrase_vec_embedding/str2vec-master/demo-data/str2vec-demo/input/sample-word-vectors-trained-by-word2vec.txt
lambda_reg: 0.149999999999999994
Max iterations: 200

load word vectors...
preparing data...
init. RAE parameters...
seed: None
shape of theta0 40300
optimizing...
Traceback (most recent call last):
  File "/users4/xyan/experiment/phrase/phrase_vec_embedding/str2vec-master/demo-data/str2vec-demo/bin/str2vec/src/nn/lbfgstrainer.py", line 353, in <module>
    args, callback=callback)
  File "/users4/xyan/experiment/phrase/phrase_vec_embedding/str2vec-master/demo-data/str2vec-demo/bin/str2vec/src/lbfgs.py", line 34, in optimize
    jac=True, options=options, callback=callback)
  File "/users4/xyan/.local/lib/python2.7/site-packages/scipy/optimize/_minimize.py", line 487, in minimize
    callback=callback, **options)
  File "/users4/xyan/.local/lib/python2.7/site-packages/scipy/optimize/lbfgsb.py", line 335, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/users4/xyan/.local/lib/python2.7/site-packages/scipy/optimize/lbfgsb.py", line 285, in func_and_grad
    f = fun(x, *args)
  File "/users4/xyan/.local/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "/users4/xyan/.local/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "/users4/xyan/experiment/phrase/phrase_vec_embedding/str2vec-master/demo-data/str2vec-demo/bin/str2vec/src/nn/lbfgstrainer.py", line 86, in compute_cost_and_grad
    total_cost = total_rec_error / total_internal_node_num + lambda_reg/2 * reg
ZeroDivisionError: division by zero

I don't know what cause this eror?Can you help me, thanks!

**Comment by pengli09** [comment]
It looks like you have a sentence of zero word in your data. Please filter them ahead.
